version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  backend:
    build: ./backend
    command: flask run --host=${FLASK_RUN_HOST:-0.0.0.0} --port=${FLASK_RUN_PORT:-5000}
    volumes:
      - ./backend:/app
      - ./instance:/app/instance
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
      - FLASK_DEBUG=${FLASK_DEBUG:-1}
    ports:
      - "${FLASK_RUN_PORT:-5000}:${FLASK_RUN_PORT:-5000}"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FLASK_RUN_PORT:-5000}/api/users"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

  worker:
    build: ./backend
    command: rq worker trello-events --url redis://redis:${REDIS_PORT:-6379}/0
    volumes:
      - ./backend:/app
      - ./instance:/app/instance
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV:-development}
    depends_on:
      redis:
        condition: service_healthy
      backend:
        condition: service_healthy
    restart: unless-stopped

  frontend:
    build: ./frontend
    command: npm run dev
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    depends_on:
      backend:
        condition: service_healthy
    restart: unless-stopped   