version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  backend:
    build: ./backend
    command: flask run --host=${FLASK_RUN_HOST:-0.0.0.0} --port=${FLASK_RUN_PORT:-5000}
    volumes:
      - ./backend:/app
      - ./instance:/app/instance
      - ./frontend/dist:/app/frontend/dist
    env_file:
      - .env
    environment:
      - FLASK_ENV=${FLASK_ENV:-production}
      - FLASK_DEBUG=${FLASK_DEBUG:-0}
    ports:
      - "${FLASK_RUN_PORT:-5000}:${FLASK_RUN_PORT:-5000}"
    depends_on:
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${FLASK_RUN_PORT:-5000}/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped   